### ISSUE TITLE
python3 broken

### ISSUE THREAD

**Issue by kaishijeng** [aidlearning/AidLearning-FrameWork#21]
On /home/facencnn, i can run
python2 ./webdemo.py OK.
However

However, I got the following error with python3
python3 ./webdemo.py

Traceback (most recent call last):
  File "webdemo.py", line 2, in <module>
    import facerecognition
ImportError: dynamic module does not define module export function (PyInit_facerecognition)

Is there a way to disable the following printout? This is quite annoying in the ssh console.

127.0.0.1 - - [01/Jun/2019 20:40:31] "POST /api/post_some_data HTTP/1.1" 200 -
127.0.0.1 - - [01/Jun/2019 20:40:31] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [01/Jun/2019 20:40:31] "POST /api/post_some_data HTTP/1.1" 200 -
127.0.0.1 - - [01/Jun/2019 20:40:31] "POST /api/post_some_data HTTP/1.1" 200 -

**Comment by aidlearning** [comment]
This is not Python 3 broken, because our encapsulated facerecoginze library only supports Python 2. You can run the mutilpose example, which supports Python 2 and 3 at the same time.
Of course, if you don't want to see debugging information, you can use a command like this
Python webpose. py > 1. log
