### ISSUE TITLE
error: Failed to create juju: opendir: Permission denied

### ISSUE THREAD

**Issue by LaviLiu** [aidlearning/AidLearning-FrameWork#43]
手机：魅族
android: 8.1
邮箱：1262221628@qq.com
root@localhost:/home/singlepose# python webpose.py libdc1394 error: Failed to create juju: opendir: Permission denied libdc1394 error: Failed to initialize libdc1394 open the cam:0 ... import tensorflow.....wait... * Running on http://0.0.0.0:5000/ (Press CTRL+C to quit) 127.0.0.1 - - [26/May/2019 16:04:56] "GET / HTTP/1.1" 200 - You choose to stop me.
运行出现上述问题？也没有收到激活邮件

**Comment by Laviyy** [comment]
垃圾邮件也没有

**Comment by aidlearning** [comment]
the error: Failed to create juju: opendir: Permission denied libdc1394 error: Failed to initialize libdc1394 is normal ,you don't need to care it. when you run the example of single pose ,You have to be patient because the Tensorflow load the models is slowly enven it load in the pc.  when I test the single pose example ,it run ok.the log as following png:

![Uploading Screenshot_2019-09-04-17-51-04-63.png…]
second,  if you cannot recieve the emails, you can give me the emails , I can activate your email Manually，sorry for the activate email not working.

**Comment by Laviyy** [comment]
My email is 1262221628@qq.com . Thank you!

**Comment by aidlearning** [comment]
the error: Failed to create juju: opendir: Permission denied libdc1394 error: Failed to initialize libdc1394 is normal ,you don't need to care it. when you run the example of single pose ,You have to be patient because the Tensorflow load the models is slowly enven it load in the pc.  when I test the single pose example ,it run ok.the log as following:

libdc1394 error: Failed to create juju: opendir: Permission denied
libdc1394 error: Failed to initialize libdc1394
import tensorflow.....wait...
remi.server      INFO     Started httpserver http://0.0.0.0:5000/
open the cam:1 ...
remi.request     INFO     built UI (path=/)


remi.server.ws   INFO     connection established: ('127.0.0.1', 41506)
remi.server.ws   INFO     handshake complete
get one frame of cam

get one frame of cam

get one frame of cam

get one frame of cam
('frames:', 0)



second,  if you cannot recieve the emails, you can give me the emails , I can activate your email Manually，sorry for the activate email not working.

**Comment by aidlearning** [comment]
Have be activated! you need login in again.

**Comment by Laviyy** [comment]
My log is:

root@localhost:/home/facencnn# python webpose.pylibdc1394 error: Failed to create juju: opendir: Permission denied
libdc1394 error: Failed to initialize libdc1394
 * Running on http://0.0.0.0:5000/ (Press CTRL+C to quit)
open the cam:1 ...
FaceRecognition Init Finished.
然后就一直卡在这里不动了，卡十几分钟也不动。
没有导入tensorflow的这个提示：
import tensorflow.....wait...

**Comment by aidlearning** [comment]
Is there a pop-up windows ? Do you have permission to open the camera?
do you try other examples is working ?

**Comment by aidlearning** [comment]
It is recommended that you delete it and reinstall it. Some bugs have been fixed recently.
http://www.aidlearning.net/downloads/aidlux-09-04.apk

**Comment by aidlearning** [comment]
have bin solved in the v0.86
