### ISSUE TITLE
Python3 failed to connect to the webcam and python2 is available. 

### ISSUE THREAD

**Issue by xiaonaoer** [aidlearning/AidLearning-FrameWork#46]
Exception information：
> 'cap. IsOpened () = = False: RTSP: / / admin: xxx@x.x.x.x'

Opencv version problem?

**Comment by aidlearning** [comment]
sorry  for reply your request. can you provide the code using webcam in python3. right code is following :
`from cvs import *`
`cap=cvs.VideoCapture(0)`
`img=cvs.read()`
`if img is None:`
`    print cam is not open!`
`else:`
`.   print cam is opened!`

**Comment by aidlearning** [comment]
don't using the cap. IsOpened () ,because the OpenCV is not support the function under the unroot termux.

**Comment by TuringZhai** [comment]
thanks！

Yes, but the code does not use 'the cap. IsOpened ()'.

The same code, only using python3.

'python3 faceID. py' in rk3399



I will also confirm it tomorrow

**Comment by aidlearning** [comment]
On some development cards, the camera number is confused. You can try Video Capture (0) or Video Capture (1).

**Comment by TuringZhai** [comment]
Capture (0) or Video Capture (1) is no problems，only in rk3399 by ‘rtsp url’. 
I will follow up.

**Comment by aidlearning** [comment]
I will find a way to support the rtsp url for videocapture...in the version 0.70(https://github.com/aidlearning/AidLearning-FrameWork/releases/tag/0.70), aid learning support the rtsp url. later version get ride of the support ,because I change the type of Gui programming.but you can try the version 0.70,it support the rstp url.

**Comment by TuringZhai** [comment]
ok ，thanks.

**Comment by TuringZhai** [comment]
Previously custom developed termux in rk3399 cluster, but no GUI.

However, due to performance problems, engineering is difficult. Currently, we are exploring arm Linux, but due to the low recognition rate of model problems (bottleneck), we are studying our face recognition part and preparing to migrate arm Linux.



Video handles getting frames that we later developed in collaboration with third parties to address performance

**Comment by aidlearning** [comment]
that's good!
