### ISSUE TITLE
Cannot use sklearn?

### ISSUE THREAD

**Issue by zwdnet** [aidlearning/AidLearning-FrameWork#54]
I install the sklearn lib using "pip3 install sklearn",then I import sklearn in the python3,there were many errors like this:
ImportError: cannot import name 'SemLock'
......
ImportError: This platform lacks a functioning sem_open implementation, therefore, the required synchronization primitives needed will not function, see issue 3770.

I found that maybe we must mount /dev/shm first then install python.
https://blog.csdn.net/u010454261/article/details/80216581 (This web is Chinese)
Could you please solve this problem? Or dose the Aid Learning not support sklearn? Thank you!

**Comment by aidlearning** [comment]
because of the aid learning don't need root privileges...so it cannot support the command:
`mount /dev/shm` so the SemLock is not supported....
but in the aidlearning support sklearn for python2.7 now..but not sklearn for python3.6...in the next version ,I will added it....thank u for for the testing..
![Screenshot_2019-09-23-14-16-07-78](https://user-images.githubusercontent.com/49776013/65404912-2482be00-de0d-11e9-8584-f7b122157b33.png)
