### ISSUE TITLE
update my python，upgrade

### ISSUE THREAD

**Issue by HLJJ** [aidlearning/AidLearning-FrameWork#6]
Can I update my python version ?if can.please tell me how to do it.Thanks.

_使用 [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github) 从我的 MI 8 发送_

**Comment by aidlearning** [comment]
you can use the apt install python to update.but i remove the source.list ,so you need touch source.list first

**Comment by HLJJ** [comment]
@aidlearning Can I touch the list address without root (my mobile phone is Android system). Or you have anyother idea to update the source. list?  Perhaps, other way that can update python? Thx for your reply. 

_使用 [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github) 从我的 MI 8 发送_

**Comment by HLJJ** [comment]
@aidlearning![Photo](https://i.imgur.com/RIrGvBE.png)

_使用 [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github) 从我的 MI 8 发送_

**Comment by aidlearning** [comment]
you can use the command:
cd /etc/apt/
touch sources.list
mkdir sources.list.d
mkdir apt.conf.d
mkdir preferences.d
vi sources.list
(write your deb src)
:wq!
apt update
it to be work.....

**Comment by HLJJ** [comment]
@aidlearning Thanks for your answer , I find the problem maybe is " No root ".Because when I vi sources.list and :wq, the wrong is " Couldn't create the sources.list".But I don't want to root it  recently. By the way thanks again. 

_使用 [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github) 从我的 MI 8 发送_

**Comment by aidlearning** [comment]
No need to root! i think you may give the AidLearningApp storage permission

**Comment by HLJJ** [comment]
@aidlearning but I think I give it storage permission ![](https://i.imgur.com/YkqXk4K.jpg)



_使用 [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github) 从我的 MI 8 发送_

**Comment by HLJJ** [comment]
And there are other questions, like these
![](https://i.imgur.com/0W4OAeJ.png)

**Comment by HLJJ** [comment]
I suddenly find that saving sources.list is ok now, but still can't "read"  the file. Look the photo, I had created all four file, and wrote the deb src. By the way, I am not sure which is the right src match aid- learning . If you know the right one, please tell me. Thanks for your helpful relpy.

**Comment by HLJJ** [comment]
@HLJJ ![The photo](https://i.imgur.com/PFs1VBL.png)

_使用 [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github) 从我的 MI 8 发送_

**Comment by aidlearning** [comment]
you can try this .in my mobile phone ,it is working
[sources.list.zip](https://github.com/aidlearning/AidLearning-FrameWork/files/3166707/sources.list.zip)

**Comment by kaishijeng** [comment]
I download sources.list.zip and unzip and put it in to /etc/apt. Got the following error when I do apt update:

Ign:1 http://deb.debian.org/debian stretch InRelease
Get:2 http://deb.debian.org/debian stretch Release [118 kB]
Get:3 http://deb.debian.org/debian stretch Release.gpg [2434 B]
Ign:3 http://deb.debian.org/debian stretch Release.gpg
Reading package lists... Done
W: GPG error: http://deb.debian.org/debian stretch Release: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 8B48AD6246925553 NO_PUBKEY 7638D0442B90D010 NO_PUBKEY EF0F382A1A7B6500
E: The repository 'http://deb.debian.org/debian stretch Release' is not signed.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.

**Comment by aidlearning** [comment]
you can try this:
[apt.zip](https://github.com/aidlearning/AidLearning-FrameWork/files/3176113/apt.zip)

**Comment by aidlearning** [comment]
I will release aidlearning 0.7:
will be surpport python3/opencv3.6/tensorflow2.0 ....
will be release in the next month....

**Comment by kaishijeng** [comment]
OK, I will wait for next release and notify me if you release it.
Can you make sure apt update/install works in your next release which will be very useful to use your SW?

Thanks,

**Comment by aidlearning** [comment]
yes!
