### ISSUE TITLE
when use 'run py3' button, the program can't start. 

### ISSUE THREAD

**Issue by Jarvis-Cai** [aidlearning/AidLearning-FrameWork#60]
hi~It's very good to use this app. And it's geat help for me. And my phone in Android 9. When I enter a program, and press the 'run py3' button, the screen just hints 'load success!', and nothing more. If I press 'run py2', it just works well. I tried the app in two different phones. They are all android 9 OS. So what's wrong with it? how can I fix this bug?

**Comment by aidlearning** [comment]
I don't know if it's because the storage space of your mobile phone is too small. I think there's also the problem of network connection during installation. I have made a new installation package. You can delete the wrong version and try to install it again. I'm looking forward to your experiment and feedback.
[app-release.apk.zip](https://github.com/aidlearning/AidLearning-FrameWork/files/3766767/app-release.apk.zip)

**Comment by Jarvis-Cai** [comment]
hi~ @aidlearning I have tried in my phone. it just the same. BTW, my phone has 4G ROM, and 15G free storage. and my phone is huawei honor 9. another phone is OPPO.

**Comment by Jarvis-Cai** [comment]
hi~ @aidlearning There is a good news. In this morning, I remove the softwate and re-install. Then it works by a miracle!!! Thanks a lot. A re-install might be helpful.

**Comment by aidlearning** [comment]
thank u for help....ios is on plan....wait !
