### ISSUE TITLE
一直停在 aid desktop loading。。。的 界面

### ISSUE THREAD

**Issue by zhaohansprt** [aidlearning/AidLearning-FrameWork#79]
手机： 是三星 note8 
系统 ： 升级安装的官方Android 9 
apk： 是在 GitHub上下载的  0.81 最新版  

如题 停在那个界面的时候  时不时的闪一个 127.0.0.1:8000 的 web error

**Comment by aidlearning** [comment]
if you can launcher the desktop which cannot loadng maybe caused  by following:
1 you have no storages when aid install and unzip the depended deb files. aid need download 1.5g deb files and need 6G storage to unzip it...most failed loading because of it
2 you dont keep the screen light or unlock in the installing processing, this may cause the downloading some dependent files failed...
3. your cpu of mobile phone is not arm64 or aarch64...now aid not support other type cpu...

**Comment by zhaohansprt** [comment]
好吧 我存储空间还有5.8个G 确实不到6G  那我再腾点地方出来 试试

**Comment by zhaohansprt** [comment]
好了 进去了 就是空间不够的问题
